/* eslint-env mocha */
/* global expect, testContext */
/* eslint-disable prefer-arrow-callback, no-unused-expressions */

import fs from 'fs'
import path from 'path'

function uncacheIndex() {
  const modulePathname = path.resolve(__dirname, '..', 'index.js')
  delete require.cache[modulePathname]
}

describe(testContext(__filename), function () {
  describe('imports and exports', function () {
    before(function () {
      uncacheIndex()
      this.commands = require('../index')
    })

    it('usage(), parse(), and commandDescriptor exist for every command', function () {
      Object.keys(this.commands).forEach(cmdName => {
        const command = this.commands[cmdName]
        expect(command.commandDescriptor).to.have.property('name')
        expect(typeof command.usage).to.equal('function')
        expect(typeof command.parse).to.equal('function')
      })
    })
  })

  describe('ignore inactive', function () {
    before(function () {
      this.cmdFilePath = cmdName => path.resolve(__dirname, '..', '..', 'config', 'commands', `${cmdName}.yaml`)
      this.testCommandDescriptorsToWrite = {
        testcmd1: `%YAML 1.2
---
command:
  name: testcmd1
  description: generated by tests (2)
  usage: testcmd1 [options] <command>
  _inactive: true
`,

        testcmd2: `%YAML 1.2
---
command:
  name: testcmd2
  description: generated by tests (1)
  usage: testcmd2 [options] <command>
  commands:
    -
      name: present
      description: this subcommand should be present
      usage: present [options]
    -
      name: ignored
      description: this subcommand should be ignored
      usage: launch [options]
      _inactive: true
`,
      }

      Object.keys(this.testCommandDescriptorsToWrite).forEach(cmdName => {
        fs.writeFileSync(this.cmdFilePath(cmdName), this.testCommandDescriptorsToWrite[cmdName])
      })

      uncacheIndex()
      this.requiredCommands = require('../index')
    })

    after(function () {
      Object.keys(this.testCommandDescriptorsToWrite).forEach(cmdName => {
        fs.unlinkSync(this.cmdFilePath(cmdName))
      })
    })

    it('ignores commands with _inactive attribute set to true', function () {
      expect(this.requiredCommands).to.not.have.property('testcmd1')
      expect(this.requiredCommands).to.have.property('testcmd2')
    })

    it('ignores subcommands with _inactive attribute set to true', function () {
      expect(this.requiredCommands).to.have.property('testcmd2')
      const foundIgnored = this.requiredCommands.testcmd2.commandDescriptor.commands.reduce((found, command) => {
        return found || command.name === 'ignored'
      }, false)
      const foundPresent = this.requiredCommands.testcmd2.commandDescriptor.commands.reduce((found, command) => {
        return found || command.name === 'present'
      }, false)
      expect(foundIgnored).to.not.be.ok
      expect(foundPresent).to.be.ok
    })
  })
})
