%YAML 1.2
---
command:
  name: review
  description: provide feedback on a project
  usage: review <project> <completeness>
  examples:
    -
      example: 'review #fantastic-falcon'
      description: Show review status and artifact URL for the fantastic-falcon project.
    -
      example: 'review #fantastic-falcon 89'
      description: Rate the completeness of the fantastic-falcon project.
